### ISSUE TITLE
Capitalizing an icon state's name and saving causes a crash

### ISSUE THREAD

**Issue by ike709** [space-wizards/RSIEdit#51]
1. open RSI
2. rename an icon state to the identical name but all caps
3. save
4. crash

```
Unhandled exception. System.IO.IOException: The process cannot access the file 'C:\Users\Ike\Documents\GitHub\CM14\CM-14\Resources\Textures\_CM14\Objects\Clothing\Mask\gas.rsi\equipped-MASK.png' because it is being used by another process.
   at System.IO.FileSystem.CopyFile(String sourceFullPath, String destFullPath, Boolean overwrite)
   at SpaceWizards.RsiLib.RSI.Rsi.SaveImagesToFolder(String rsiFolder) in C:\Users\Ike\Documents\GitHub\SS14\RSIEdit\RSIEdit\RSI.NET\SpaceWizards.RsiLib\RSI\Rsi.cs:line 124
   at SpaceWizards.RsiLib.RSI.Rsi.SaveToFolder(String rsiFolder) in C:\Users\Ike\Documents\GitHub\SS14\RSIEdit\RSIEdit\RSI.NET\SpaceWizards.RsiLib\RSI\Rsi.cs:line 105
   at Editor.ViewModels.RsiItemViewModel.Save() in C:\Users\Ike\Documents\GitHub\SS14\RSIEdit\RSIEdit\Editor\ViewModels\RsiItemViewModel.cs:line 628
   at Editor.ViewModels.MainWindowViewModel.Save() in C:\Users\Ike\Documents\GitHub\SS14\RSIEdit\RSIEdit\Editor\ViewModels\MainWindowViewModel.cs:line 276
   at Avalonia.Data.Converters.MethodToCommandConverter.Execute(Object parameter) in /_/src/Avalonia.Base/Data/Converters/MethodToCommandConverter.cs:line 82
   at Avalonia.Input.KeyBinding.TryHandle(KeyEventArgs args) in /_/src/Avalonia.Input/KeyBinding.cs:line 41
   at Avalonia.Input.KeyboardDevice.ProcessRawEvent(RawInputEventArgs e) in /_/src/Avalonia.Input/KeyboardDevice.cs:line 241
   ```

**Comment by ike709** [comment]
Fixed in 0.6.3
